package de.neemann.oscilloscope.draw.elements;

import de.neemann.oscilloscope.signal.PeriodicSignal;

/**
 * A BNC output connector
 */
public class BNCOutput extends BNC<BNCOutput> {
    private OutputGetter getter;

    /**
     * Creates an input
     *
     * @param name the name of the input
     */
    public BNCOutput(String name) {
        super(name);
    }


    /**
     * Sets the signal getter.
     *
     * @param getter Interface which allows to fetch the signal
     * @return this for chained calls
     */
    public BNCOutput setOutput(OutputGetter getter) {
        this.getter = getter;
        return this;
    }

    /**
     * @return the signal generated by this output
     */
    public PeriodicSignal getOutput() {
        return getter.getSignal();
    }

    /**
     * The output getter
     * Is used by the connector to fetch the signal it outputs
     */
    public interface OutputGetter {
        /**
         * @return the signal
         */
        PeriodicSignal getSignal();
    }
}
